### ISSUE TITLE
Add "wait-for"  to golang/builder-exp

### ISSUE THREAD

**Issue by relax-admin** [pangpanglabs/dockerfiles#4]
In the microservices test, in order to ensure the independence of the data, you need to start all microservices, and all its dependencies, including the independent mysql

Known: micro-service (go-api) depends on mysql

Actual: The following docker-compose.yml will cause the go-api to fail to start, because depends_on will not wait for the container ready

error config
```yml
version: "3"
services:
 mysql-server:
   container_name: test-mysql
   environment:
   - MYSQL_ROOT_PASSWORD=1234
   image: mysql:5.7.22
   ports:
   - 3306
   volumes:
   - ./database/mysql/:/docker-entrypoint-initdb.d
 ping-mysql-server:
   container_name: test-ping-mysql
   depends_on:
   - mysql-server
   environment:
   - MYSQL_HOST=test-mysql
   - PORT=3306
   - USER_NAME=root
   - PASSWORD=1234
   image: xiaoxinmiao/ping-mysql
   ports:
   - 8080
```

Expect: go-api starts after mysql ready

Solution: add wait-for to the dockerfile

right config
```yml
version: "3"
services:
 mysql-server:
   container_name: test-mysql
   environment:
   - MYSQL_ROOT_PASSWORD=1234
   image: mysql:5.7.22
   ports:
   - 3306
   volumes:
   - ./database/mysql/:/docker-entrypoint-initdb.d
 ping-mysql-server:
   container_name: test-ping-mysql
   command: sh -c 'echo "wait mysql..." && /go/bin/wait-for.sh test-mysql:3306 -t 36000 -- ./ping-mysql'
   depends_on:
   - mysql-server
   environment:
   - MYSQL_HOST=test-mysql
   - PORT=3306
   - USER_NAME=root
   - PASSWORD=1234
   image: xiaoxinmiao/ping-mysql
   ports:
   - 8080
```

```dockerfile
FROM golang AS builder

WORKDIR /go/src/ping-mysql
COPY . .
# disable cgo
ENV CGO_ENABLED=0
# build steps
RUN echo ">>> 1: go version" && go version
#RUN echo ">>> 2: go get" && go get -v -d
RUN echo ">>> 3: go install" && go install

FROM alpine
WORKDIR /go/bin/
COPY --from=builder /go/bin/ping-mysql ./ping-mysql
COPY --from=builder /wait-for/wait-for.sh ./wait-for.sh
RUN chmod +x ./wait-for.sh
EXPOSE 8080
CMD ["./ping-mysql"]
```

reference:
- Control startup and shutdown order in Compose [Control startup and shutdown order in Compose](https://docs.docker.com/compose/startup-order/)
- wait-for [wait-for](https://github.com/Eficode/wait-for)
